### ISSUE TITLE
GLANCE_OFF not working

### ISSUE THREAD

**Issue by sharma-ji** [eouia/MMM-Glance#1]
I made a module which sends the GLANCE_OFF notification but instead i got the below error in console 

![capture3](https://user-images.githubusercontent.com/17575809/31079758-5870e1a2-a7a4-11e7-9a56-028a4fd67f24.PNG)

**Comment by eouia** [comment]
sorry. I misspelled in last commit. I will modify. you can edit it by "glaceOff" -> "glanceOff" in line 198.
ps. I've commited

**Comment by sharma-ji** [comment]
@eouia Thanks for your reply. I got one more question, can I remove the timer?  Such that I can evoke any module by notification and hide it again by GLANCE_OFF ? I need to do it manually rather than timer, how to do that ?
Thanks in advance

**Comment by eouia** [comment]
How about giving enough time like 10000000000 millisec?
