### ISSUE TITLE
How do I hide a module to be revealed only when called by GLANCE_ON?

### ISSUE THREAD

**Issue by raz0rf0x** [eouia/MMM-Glance#2]
I can't seem to figure out how to do that. If I hide a module with MMM-Remote-Control and call it with GLANCE_ON, all I get is a blank screen.

**Comment by eouia** [comment]
That's not a bug. MM's show/hide mechanism work with its locking system, because preventing unintended show/hide by other modules.
Anyway, you can modify source code with this;
In Line 151 and Line 176; 
```
m.show(0)
```
change code with this;
```
m.show(0, {force:true})
```
